### ISSUE TITLE
Implement key generation BIP44 path with 3 components

### ISSUE THREAD

**Issue by StreamOfMaya** [Zondax/wallet-core#2]
Concurrent support for BIP32-Ed25519 to ADR 0008 (i.e. SLIP-0010). Seamless switching between old and new derivation based on path.

- Use old BIP32-Ed25519 when path has 5 items (BIP44)
- Use SLIP-0010 when page has 3 items (BIP32)

**Comment by jleni** [comment]
We need to support both in Ledger app, however, in wallet-core this is not necessary.

We need to revert back and support ONLY SLIP0010 and 3 items.

**Comment by emmanuelm41** [comment]
Feature created [here](https://github.com/trustwallet/wallet-core/pull/1440)!

**Comment by emmanuelm41** [comment]
Trustwallet merged the PR. We can close this issue.
